# Generated by Django 5.1.1 on 2024-12-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('deccription', models.TextField()),
                ('image', models.ImageField(upload_to='service/images/')),
            ],
        ),
    ]
