# Generated by Django 5.1.1 on 2024-12-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availlableTime',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availlableTime',
            field=models.ManyToManyField(to='doctor.availlabletime'),
        ),
    ]
